config/routes.rb
Rails.application.routes.draw do
  root to:'static_pages#top'
  resources :menus
  get 'random', to: 'menus#random'
  get '/menus/:id/material_preperation', to: 'menus#material_preperation', as: 'material_preparation'
  get '/menus/:id/cooking', to: 'menus#cooking', as: 'cooking'
  get 'menus/:id/success', to: 'menus#success', as: 'success'
  get 'menus/:id/time_up', to: 'menus#time_up', as: 'time_up'
  get 'menus/:id/failure', to: 'menus#failure', as: 'failure'
  get 'menus/:id/recipe', to: 'menus#recipe', as: 'recipe'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :menu
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :materials
  has_many :recipes
  has_many :menu_tools
  has_many :tools, through: :menu_tools
  accepts_nested_attributes_for :menu_tools
end

app/models/menu_tool.rb
class MenuTool < ApplicationRecord
  belongs_to :menu
  belongs_to :tool
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :menu
end

app/models/tool.rb
class Tool < ApplicationRecord
  has_many :menu_tools
  has_many :menus, through: :menu_tools
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy, :material_preperation, :cooking, :success, :time_up, :failure, :recipe]

  def random
    @menu = Menu.where( 'id >= ?', rand(Menu.count) + 1 ).first
  end

  def material_preperation
  end

  def cooking
  end

  def success

  end

  def time_up
  end

  def failure
  end

  def recipe
  end

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:title, :recipe, :cooking_time, :image_url, :taste, :hint1, :hint2, :hint3, :person_count)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end

  def success
  end

  def time_up
  end

  def failure
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HideRecipe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src='https://code.jquery.com/jquery-2.1.4.js'></script>

<!--    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.css' />-->
<!--    <script src='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.js'></script>-->
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |form| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :recipe %>
    <%= form.text_area :recipe %>
  </div>

  <div class="field">
    <%= form.label :cooking_time %>
    <%= form.number_field :cooking_time %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :taste %>
    <%= form.text_area :taste %>
  </div>

  <div class="field">
    <%= form.label :hint1 %>
    <%= form.text_area :hint1 %>
  </div>

  <div class="field">
    <%= form.label :hint2 %>
    <%= form.text_area :hint2 %>
  </div>

  <div class="field">
    <%= form.label :hint3 %>
    <%= form.text_area :hint3 %>
  </div>

  <div class="field">
    <%= form.label :person_count %>
    <%= form.text_field :person_count %>
  </div>

<!--  <div class="actions">-->
    <%#= form.submit %>
<!--  </div>-->
  <a class="btn-floating disabled"><i class="material-icons">add</i></a>
  <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right"></i>
  </button>
<% end %>

app/views/menus/cooking.html.erb
<div class="cooking-content">
  <h4>TIME</h4>

  <h1><span id="min"></span>:<span id="sec"></span></h1>

  <a id="hint-button" class="waves-effect waves-light btn modal-trigger top-btn" href="#modal1" onclick="hintCount()">
    <i class="material-icons left">live_help</i>ヒント あと<span id="hint">3</span>回</a>
  <a id="detail-button" class="waves-effect waves-light btn modal-trigger top-btn" href="#modal2" onclick="detailCount()">
    <i class="material-icons left">list</i>詳細</a>
  <div class="cooking-image">
    <%= image_tag @menu.image_url, size: '375x375' %>
    <%= link_to success_path(@menu), class: 'waves-effect waves-light main-button btn-large image-btn' do %>
      <i class="material-icons left">local_dining</i>完成<i class="material-icons right">local_dining</i>
    <% end %>
  </div>
  <!--ここはモーダルで表示-->
  <div class="give-up">
    <a class="modal-trigger give" href="#modal3">ギブアップ</a>
  </div>
  <!--モーダル-->
  <div id="modal1" class="modal">
    <a href="#" class="modal-close waves-effect waves-green btn-flat">
      <i class="material-icons cancel">cancel</i>
    </a>
    <div class="modal-content">
      <div id="hint1">
        <h4>ヒント1</h4>
        <p><%= @menu.hint1 %></p>
      </div>
      <div id="hint2" class="hidden">
        <h4>ヒント2</h4>
        <p><%= @menu.hint2 %></p>
      </div>
      <div id="hint3" class="hidden">
        <h4>ヒント3</h4>
        <p><%= @menu.hint3 %></p>
      </div>
    </div>
<!--    <div class="modal-footer">-->
<!--      <a href="#" class="modal-close waves-effect waves-green btn-flat">Agree</a>-->
<!--    </div>-->
  </div>

  <div id="modal2" class="modal">
    <a href="#" class="modal-close waves-effect waves-green btn-flat">
      <i class="material-icons cancel">cancel</i>
    </a>
    <div class="modal-content">
      <strong>食材:</strong>
      <ul class="collection">
        <% @menu.materials.each do |material| %>
          <li class="collection-item"><%= material.name %><%= material.quantity %></li>
        <% end %>
      </ul>
    </div>

<!--    <div class="modal-footer">-->
<!--      <a href="" class="modal-close waves-effect waves-green btn-flat">Agree</a>-->
<!--    </div>-->
  </div>

  <div id="modal3" class="modal">
    <a href="#" class="modal-close waves-effect waves-green btn-flat">
      <i class="material-icons cancel">cancel</i>
    </a>
    <div class="modal-content">
     本当にギブアップしますか？
    </div>
    <%= link_to 'はい', failure_path(@menu), class: 'waves-effect waves-light btn main-button back' %>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    // document.addEventListener('DOMContentLoaded', function() {
    //     var elems = document.querySelectorAll('.modal');
    //     var instances = M.Modal.init(elems, options);
    // });

    // Or with jQuery
    var cooktimer;
    var min = <%= @menu.cooking_time %> + 0;
    var sec = 0;
    var count = 3;
    function cntStart()
    {
        cooktimer = <%= @menu.cooking_time %>
            // console.log(cooktimer)
            cooktimer = setInterval("countDown()",1000);
    }

    function countDown()
    {
        // console.log(sec)
        // console.log(min)
        if (localStorage.getItem("countTimer") == null) {
            localStorage.setItem("countTimer", 'active');
        } else {
            min = $('#min').text();
            sec = $('#sec').text();
        }

        if (min=="") min=0;
        min=parseInt(min);

        if (sec=="") sec=0;
        sec=parseInt(sec);

        tmWrite(min*60+sec-1);
    }

    function tmWrite(int)
    {
        int=parseInt(int);

        // console.log(int);
        if (int<=0)
        {
            // ここがタイムアップ
            // alert("時間です！");
            window.location.href = `<%= time_up_path(@menu) %>`;
        }
        else
        {
            // console.log(int);
            //残り分数はintを60で割って切り捨てる
            // document.timer.elements[0].value=Math.floor(int/60);
            $('#min').text(`${Math.floor(int/60)}`);
            //残り秒数はintを60で割った余り
            // document.timer.elements[1].value=int % 60;
            $('#sec').text(`${int % 60}`);
        }
    }

    var hintCount = function () {
        if (count > 0) {
            count = count - 1;
            $('#hint').text(count);
            if (count == 1) {
                $('#hint2').removeClass('hidden');
            } else if (count == 0) {
                $('#hint3').removeClass('hidden');
            }
        }
        $('#detail-button').removeClass('top-btn-under-line');
        $('#hint-button').addClass('top-btn-under-line');
    }

    var detailCount = function () {
        $('#detail-button').addClass('top-btn-under-line');
        $('#hint-button').removeClass('top-btn-under-line');
    }

    // 画面繊維した時点で始まる
    $(document).ready(function(){
        cntStart();
        localStorage.removeItem("countTimer");
        $('.modal').modal();
    });


</script>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/failure.html.erb
<div class="result-content">
  <h2>残念！</h2>

  <%= image_tag 'result/failure.png', size: '375x375' %>

  <h3>想像力が足りないよ？</h3>
  <%= link_to recipe_path(@menu), class: 'waves-effect waves-light btn-large main-button' do %>
    <i class="material-icons left">search</i>
    レシピを確認する
  <% end %>
</div>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menus</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Recipe</th>
      <th>Cooking time</th>
      <th>Image url</th>
      <th>Taste</th>
      <th>Hint1</th>
      <th>Hint2</th>
      <th>Hint3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.title %></td>
        <td><%= menu.recipe %></td>
        <td><%= menu.cooking_time %></td>
        <td><%= menu.image_url %></td>
        <td><%= menu.taste %></td>
        <td><%= menu.hint1 %></td>
        <td><%= menu.hint2 %></td>
        <td><%= menu.hint3 %></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/material_preperation.html.erb
<div class="preperation-content">
  <h4 class="content-name">料理が決定しました！</h4>
  <%= image_tag @menu.image_url, size: '375x375' %>

  <h4 class="content-name title"><%= @menu.title %></h4>
  <p class="cook-time">調理時間 <%= @menu.cooking_time %>分</p>

  <%= image_tag 'sa-tuku.png', width: '375', class: 'explain' %>
  <%= image_tag 'pre-mate1.png', width: '375', class: 'explain'  %>
  <%= image_tag 'pre-mate2.png', width: '375', class: 'explain'   %>
  <%= image_tag 'pre-mate3.png', width: '375', class: 'explain'   %>

  <div class="material-memo">
    <h5 class="content-name">食材メモ <span class="person-count"><%= @menu.person_count %>人前</span></h5>
    <hr>
    <ul class="collection">
      <% @menu.materials.each do |material| %>
        <li class="collection-item">
          <input type="checkbox" />
          <span class="material"><%= material.name %></span>
          <span class="quantity"><%= material.quantity %></span>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="material-button-gruop">
    <%= link_to '#modal1', class: 'waves-effect waves-light btn-large modal-trigger main-button cook-start' do %>
      クッキングスタート
    <% end %>
<!--    <a class="waves-effect waves-light btn modal-trigger main-button" href="#modal1">ヒント</a>-->

    <%= link_to random_path, class: 'waves-effect waves-light btn main-button back' do %>
      <i class="material-icons left">chevron_left</i>料理選択画面に戻る
    <% end %>
  </div>
</div>

<!--モーダル-->
<div id="modal1" class="modal">
  <div class="modal-content">
    <p>タイマーがスタートしますよろしいですか？</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="modal-close waves-effect waves-green btn-flat">キャンセル</a>
    <%= link_to 'はい', cooking_path(@menu), class: 'waves-effect waves-light btn main-button back' %>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    var clickCount = 0;

    // 画面繊維した時点で始まる
    $(document).ready(function(){
        localStorage.removeItem("countTimer");
        $('.modal').modal();
    });
</script>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>


<!--モーダル部品-->
<!-- Modal Trigger -->
<a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>

<!-- Modal Structure -->
<div id="modal1" class="modal">
  <div class="modal-content">
    <h4>Modal Header</h4>
    <p>A bunch of text</p>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>
  </div>
</div>

app/views/menus/random.html.erb
<!--<p id="notice"><%#= notice %></p>-->
<div class="food-select-content">
  <div class="image-content">
    <%= image_tag @menu.image_url, size: '375x375' %>

    <!--TODO ボタンのアイコン変える リンク先-->
    <div class="image-btn-group">
      <%= link_to material_preparation_path(@menu), class: 'waves-effect waves-light main-button btn-large image-btn' do %>
        <i class="material-icons left">check</i>この料理に決定
      <% end %>
      <a class="waves-effect waves-light main-button btn-large ano-image-btn" href="/random"><i class="material-icons left">cached</i>別の料理</a>
    </div>
  </div>
  <div class="select-content">
    <h4 class="title">
      <%= @menu.title %>
    </h4>

    <p>
      <strong>調理時間:</strong>
      <%= @menu.cooking_time %> 分
    </p>

    <p>
    <h5 class="content-name">調理器具</h5>
    <hr>
    <% @menu.tools.each do |tool|  %>
      <span class="tool-badge"><%= tool.name %></span>
    <% end %>
    </p>

    <h5 class="content-name">食材 <span class="person-count"><%= @menu.person_count %>人前</span></h5>
    <hr>
    <ul class="collection">
      <% @menu.materials.each do |material| %>
        <li class="collection-item">
          <span class="material"><%= material.name %></span>
          <span class="quantity"><%= material.quantity %></span>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<!--<%#= link_to 'Edit', edit_menu_path(@menu) %> |-->
<%#= link_to 'Back', menus_path %>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        localStorage.removeItem("countTimer");
    });
</script>

app/views/menus/recipe.html.erb
<div class="recipe-content">
  <%= image_tag 'logo.png', width: '375px', class: 'logo' %>
  <h2><%= @menu.title %></h2>
  <%= image_tag 'recipe/make.png', width: '375' %>
  <% @menu.recipes.each_with_index do |recipe, index| %>
    <div class="r-content recipe">
      <strong><%= index+1 %>.</strong>
      <%= simple_format(recipe.content) %>
    </div>
  <% end %>
  <%= image_tag 'recipe/umaku.png', width: '375', class: 'umaku'%>
  <div class="r-content">
    <h3>あなた達の料理を</h3>
    <h3>友達にシェアしましょう！</h3>
  </div>

  <div class="r-content t-content">
    <div class="twitter">
      <a href="//twitter.com/share" class="twitter-share-button" data-text="<%= @menu.title %>を作りました！ レシピのかくれんぼ" data-url="https://hidden-recipe.herokuapp.com/" data-lang="ja<!-- 日本語の場合 -->">
        <%= image_tag 'recipe/twitter.png', size: '60x60', class: 'twitter-image' %>
      </a>
    </div>
    <a class="waves-effect waves-light btn-large main-button" href="/">
      <i class="material-icons left">local_cafe</i>
      トップへ
    </a>
  </div>
</div>

<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @menu.title %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @menu.recipe %>
</p>

<p>
  <strong>Cooking time:</strong>
  <%= @menu.cooking_time %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @menu.image_url %>
</p>

<p>
  <strong>Taste:</strong>
  <%= @menu.taste %>
</p>

<p>
  <strong>Hint1:</strong>
  <%= @menu.hint1 %>
</p>

<p>
  <strong>Hint2:</strong>
  <%= @menu.hint2 %>
</p>

<p>
  <strong>Hint3:</strong>
  <%= @menu.hint3 %>
</p>

<p>
  <strong>person_count:</strong>
  <%= @menu.person_count %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/menus/success.html.erb
<div class="result-content">
  <h2>おめでとう！</h2>

  <%= image_tag 'result/success.png', size: '375x375' %>

  <h3>おいしくできましたか？</h3>
  <%= link_to recipe_path(@menu), class: 'waves-effect waves-light btn-large main-button' do %>
    <i class="material-icons left">search</i>
    レシピを確認する
  <% end %>
</div>

app/views/menus/time_up.html.erb
<div class="result-content">
  <h2>タイムアップ！</h2>

  <%= image_tag 'result/timeup.png', size: '375x375' %>

  <h3>料理は完成しましたか？</h3>
  <%= link_to recipe_path(@menu), class: 'waves-effect waves-light btn-large main-button' do %>
    <i class="material-icons left">search</i>
    レシピを確認する
  <% end %>
</div>

app/views/static_pages/top.html.erb
<div class="top-content">
  <%= image_tag 'logo.png', width: '375px', class: 'logo' %>
  <%= image_tag 'chara.png', width: '375px', class: 'logo' %>
  <%= image_tag 'explain.png', width: '375px', class: 'logo' %>
  <a class="waves-effect waves-light btn-large main-button top-btn" href="/random">
    <i class="material-icons left">local_dining</i>料理をはじめる</a>
</div>